name: True Quit
favicon: null
layout_spectrum: 0.88126
typography_spectrum: 0.85541
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a7d367'
    - '#ffffff'
    - '#76a01d'
    - '#34640d'
    - '#132202'
  brandStrength: 0.15920217521488667
  lightness: 0.9853095491416752
  saturation: 0.5370069360360503
  rhythmicContrast: 0.9225765673909336
purpose: []
